"""Regenerates ``flex_asana._generated_users.User`` from the Asana workspace's
member list, for IDE autocomplete on ``Experiment(user=...)``. Run whenever
people join or leave:

    python -m flex_asana.update_users
"""

from __future__ import annotations

import os
from pathlib import Path

from flex_asana.client import AsanaClient
from flex_asana.sync import handle_from_user

_OUT = Path(__file__).parent / "_generated_users.py"


def main() -> None:
    client = AsanaClient()
    workspace_gid = os.environ.get("ASANA_WORKSPACE_GID") or client.default_workspace_gid()
    handles = sorted({h for u in client.list_users(workspace_gid) if (h := handle_from_user(u))})
    if not handles:
        raise RuntimeError("No Asana users found; nothing written.")

    literal = ", ".join(repr(h) for h in handles)
    _OUT.write_text(
        '"""Auto-generated by `python -m flex_asana.update_users` from the Asana\n'
        'workspace member list. Do not edit by hand."""\n\n'
        "from typing import Literal\n\n"
        f"User = Literal[{literal}]\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(handles)} user handles to {_OUT}")


if __name__ == "__main__":
    main()
